### ISSUE TITLE
Export fails with "Export all" option

### ISSUE THREAD

**Issue by tkedwards** [darekkay/todoist-export#18] opened 2022-12-06 23:18 UTC
Thanks for fixing https://github.com/darekkay/todoist-export/issues/17

But it still doesn't seem to work, or there's something else going in:

```
git clone https://github.com/darekkay/todoist-export.git
cd todoist-export/
cp src/config.js.example src/config.js
vim src/config.js  # created new application, added the client ID and client secret
npm install
npm start
```

```
$ npm start

> todoist-export@1.3.0 start
> node src/index.js

Server running at http://localhost:3000
GET / 302
GET /todoist-export -
GET /todoist-export/ 200
POST /todoist-export/auth 302
GET /todoist-export/?code=xxx&state=json_all 200
GET /todoist-export/export?code=xxx&format=json_all 302
GET /todoist-export/?token=xxx&format=json_all 304
✖ Request failed with status code 404
GET /todoist-export/download?token=xxx&format=json_all 500

```

And in the browser I get:
```
Request failed with status code 404

Error: Request failed with status code 404
    at createError (/home/tim/bin/todoist-export/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/tim/bin/todoist-export/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/tim/bin/todoist-export/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[Please try again](http://localhost:3000/todoist-export/)
```

**Comment by darekkay** [comment] 2022-12-07 07:38
@tkedwards Please don't post your `code` or `token` - this is sufficient for _anyone_ to access all your Todoist data. I've edited your post, but it can be still viewed in the history. I highly suggest that you revoke this access token to prevent further access.

With that said, I did use your token with the latest version of this project to debug the issue and I was able to download your data (I've immediately deleted it without opening). However, I was able to reproduce the issue when selecting the "Export all" checkbox. This issue exists for a few weeks/months now, but I haven't come around looking into it, yet.

**Comment by darekkay** [comment] 2022-12-07 10:12
Fixed in a72fb5ddfe362df381ac23258bf380d756d9ffb9 . @tkedwards Please double-check if the solution works for you.

**Comment by tkedwards** [comment] 2022-12-08 02:28
Oops! I've deleted that app with that client ID and secret now from https://developer.todoist.com/appconsole.html

I've tried the same steps as before, including creating a  new app at https://developer.todoist.com/appconsole.html:

```
git clone https://github.com/darekkay/todoist-export.git
cd todoist-export/
cp src/config.js.example src/config.js
vim src/config.js  # created new application, added the client ID and client secret
npm install
npm start
```

But now I get a different error:

```
$ npm start

> todoist-export@1.3.0 start
> node src/index.js

/home/tim/bin/todoist-export/src/app.js:49
      status: error.response?.status,
                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/tim/bin/todoist-export/src/index.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Comment by darekkay** [comment] 2022-12-08 07:45
Looks like an issue with [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). Which Node version do you have? Optional chaining is supported since Node 14, anything below Node 14 is officially [not supported anymore](https://github.com/nodejs/release#release-schedule).

**Comment by darekkay** [comment] 2022-12-08 08:50
FYI, there was yet another issue when _exporting huge amount of data_. After ~35.000 tasks, Todoist returned 'Unknown error. If it keeps happening, please get in touch with Todoist Support.'.

As a workaround, the export will now return all the data it received before the API returns an error. So it might be missing tasks, but at least it will not fail anymore. 

Fixed in 0f8d6c9aed2929bbc249aed0dad2761b4d5cc7a5

**Comment by darekkay** [comment] 2022-12-08 09:45
I'll close the ticket. If you still encounter any issues (with Node 14+), please add a comment and I'll reopen it.

**Closed as completed by darekkay** 2022-12-08 09:45 UTC
Labels: Type: Bug

**Comment by tkedwards** [comment] 2022-12-08 10:53
@darekkay 
Thanks for all your help! I'm on Ubuntu 22.04, so default node JS version is `12.<something>`. Once I upgraded using NVM all is now working.

In case it helps anyone else here are full steps to get latest todoist-export working on Ubuntu 22.04:
```
# Ubuntu 22.04 only - install a more recent version of Node JS as todoist-export needs Node 14.0 or newer
# Install Node Version Manager https://github.com/nvm-sh/nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
nvm install node
# Exit terminal with ctrl+d, open a new terminal (or tab in Konsole)

git clone https://github.com/darekkay/todoist-export.git
cd todoist-export/
cp src/config.js.example src/config.js
vim src/config.js  # Follow the steps in README.md to create new integration in Todoist account, and setup todoist-export to do OAuth
node -v # This should be newer than version 14
npm install
npm start
```
